### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by Chrisbrns** [UpstreamAB/KaseyaVSAPowerPack#1]
When importing the xml file via system->import center, it gives error and only imports half the items. Also same issue when pasting the code.
![script error](https://user-images.githubusercontent.com/5501752/46760259-936c1300-cc9f-11e8-9390-6dba255e1bc5.JPG)

**Comment by Pr1meTimeTVx** [comment]
Same error for me as well.
Are you also missing Windows scripts?

**Comment by Pr1meTimeTVx** [comment]
I am assuming because the Read Me mentions Windows Scripts for O365 and Win 10 updates etc etc, but there is no Windows folder. I created a second Issue thread.

**Comment by ecspresso** [comment]
I will talk to Ronny and see if can fix this on Monday.

**Comment by Chrisbrns** [comment]
Great!

—

Chris Burns

Dedicated IT
Mobile 321-750-5885
Direct 321-586-1101

Sent from my iPhone

________________________________

**Comment by ecspresso** [comment]
I reuploaded procedures without the failing script. Keeping this issue open for now to give us a change to have a look at it and hopefully fix it (and upload again with working script).

**Comment by Pr1meTimeTVx** [comment]
IS everything fixed with the import now?

**Comment by ecspresso** [comment]
Yes, the import works (we removed the faulting script). Closing this to avoid further confusion, I will upload the new version when the faulting script is fixed.
