### ISSUE TITLE
Error importing xml file

### ISSUE THREAD

**Issue by max-singh** [UpstreamAB/KaseyaVSAPowerPack#3]
Hi,

As per discussion with Emile Priller, Upstream support I'm submitting this issue on GitHub.

I'm getting following error while importing 3rd party application mgmnt.xml:

**The file you are trying to import is not formatted correctly. It contains invalid XML.**

![image](https://user-images.githubusercontent.com/41486885/47649529-f42a9500-db53-11e8-8c8f-041cd11d7ccf.png)

We are on Kaseya VSA 9.5.0.7.

**Comment by ecspresso** [comment]
My best guess is that something is missing from the file. [Open this link](https://raw.githubusercontent.com/UpstreamAB/KaseyaVSAPowerPack/master/AgentProcedures/3rd%20Party%20Application%20Mgmnt.xml), right click anywhere and select "save page as". Save the file and import it. Let me know how it goes.

**Comment by max-singh** [comment]
Hi Emile, thanks for the suggestion - it worked :)

![image](https://user-images.githubusercontent.com/41486885/47653173-4670b380-db5e-11e8-8a70-c0892a4bf094.png)

**Comment by ecspresso** [comment]
Great!
